version: '3'

services:
  auth:
    image: ghcr.io/cludch/csgo-tools/csgo-tools:latest
    command: "./auth"
    container_name: auth
    restart: unless-stopped
    depends_on:
      - db
    volumes: 
      - ./configs:/app/configs

  valveapiclient:
    image: ghcr.io/cludch/csgo-tools/csgo-tools:latest
    command: "./valveapiclient"
    container_name: valveapiclient
    restart: unless-stopped
    depends_on:
      - db
    volumes: 
      - ./configs:/app/configs

  faceitapiclient:
    image: ghcr.io/cludch/csgo-tools/csgo-tools:latest
    command: "./faceitapiclient"
    container_name: faceitapiclient
    restart: unless-stopped
    depends_on:
      - db
    volumes: 
      - ./configs:/app/configs

  demodownloader:
    image: ghcr.io/cludch/csgo-tools/csgo-tools:latest
    command: "./demodownloader"
    container_name: demodownloader
    restart: unless-stopped
    depends_on:
      - db
    volumes: 
      - ./demos:/demos
      - ./configs:/app/configs

  gameclient:
    image: ghcr.io/cludch/csgo-tools/csgo-tools:latest
    command: "./gameclient"
    container_name: gameclient
    restart: unless-stopped
    depends_on:
      - db
    volumes: 
      - ./demos:/demos
      - ./configs:/app/configs

  demoparser:
    image: ghcr.io/cludch/csgo-tools/csgo-tools:latest
    command: "./demoparser"
    container_name: demoparser
    restart: unless-stopped
    depends_on:
      - db
    volumes: 
      - ./demos:/demos
      - ./configs:/app/configs
  
  api:
    image: cludch/csgo-tools:latest
    command: "./restapi"
    container_name: api
    restart: unless-stopped
    depends_on:
      - db
    volumes: 
      - ./configs:/app/configs

  db:
    image: mongo:4.4
    container_name: csgo_mongodb
    restart: unless-stopped
    ports:
      - 127.0.0.1:27017:27017
    env_file: docker.env
    volumes: 
      - ./database:/data/db
